[package]
name = "tcp-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
output = []
default = []

[dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
